using System.Diagnostics;
using System.Text;
using GBARecomp.ARM;
using static GBARecomp.ARM.Registers;

namespace GBARecomp;

internal sealed class CSharpGenerator
{
    private const string FileFooter = "}\n";
    private const string EventCheck = "if (Scheduler.Cycles >= Scheduler.NextEvent) Recomp.HandleEvents(ctx);";

    private readonly Context _context;
    private readonly Dictionary<uint, string> _functionNames;

    public CSharpGenerator(Context context)
    {
        _context = context;
        _functionNames = AssignFunctionNames(context.Functions);
    }

    private string FileHeader => Lines(
    [
        "// Generated by GBARecomp.",
        "#pragma warning disable CS0162, CS0164, CS0219",
        "",
        .. _context.RecompInclude.ReplaceLineEndings("\n").Split('\n'),
        "",
        "namespace RecompiledFuncs;",
        "",
        "public static partial class Funcs",
        "{",
    ]);

    public string FunctionName(Function function) => _functionNames[function.Address];

    public string GenerateFile(IEnumerable<string> methods)
    {
        return FileHeader + string.Join("\n", methods) + FileFooter;
    }

    public string Generate(FunctionAnalysis analysis)
    {
        if (analysis.Errors.Count > 0)
        {
            throw new ArgumentException($"{analysis.Function.Name} has analysis errors.", nameof(analysis));
        }

        return new FunctionWriter(this, analysis).Write();
    }

    public string GenerateUnrecompiled(Function function)
    {
        string name = FunctionName(function);
        string signature = $"public static void {name}(RecompContext ctx)";
        string[] method = _context.Stubs.Contains(function.Name)
            ? [$"        {signature}", "        {", "        }"]
            : [$"        {signature} => throw new NotImplementedException(\"{function.Name} is in patches.ignored and nothing replaced it.\");"];

        return Lines([$"    {signature} => Patches.{name}(ctx);", "", "    public static partial class Original", "    {", .. method, "    }"]);
    }

    public string GenerateTables()
    {
        var lines = new List<string>();
        if (_context.TraceMode)
        {
            lines.AddRange(["    static partial void TraceEntry(string function);", ""]);
        }

        lines.AddRange(["    public static readonly (uint Address, RecompFunc Function)[] Table =", "    ["]);
        lines.AddRange(_context.Functions.Select(f => $"        (0x{f.Address:X8}, {FunctionName(f)}),"));
        lines.AddRange(["    ];", "", "    public static readonly (uint Address, uint Size, RecompFunc Function)[] RAMFunctions =", "    ["]);
        lines.AddRange(_context.Functions.Where(f => f.IsCopiedToRAM).Select(f => $"        (0x{f.Address:X8}, 0x{f.Size:X}, {FunctionName(f)}),"));
        lines.AddRange(["    ];", ""]);
        lines.Add("    /// <summary>Every function in the game, ready for mods to replace or hook with Mod.Replace and Mod.Hook.</summary>");
        lines.AddRange(["    public static class Patches", "    {"]);
        lines.AddRange(_context.Functions.Select(f => $"        public static RecompFunc {FunctionName(f)} = Original.{FunctionName(f)};"));
        lines.Add("    }");

        return GenerateFile([Lines(lines)]);
    }

    public string GenerateData()
    {
        var used = new HashSet<string>();
        return Lines(
        [
            "// Generated by GBARecomp.",
            "",
            "namespace RecompiledFuncs;",
            "",
            "/// <summary>The address of everything in the game that isn't code, by its symbol name.</summary>",
            "public static class Data",
            "{",
            .. _context.DataSymbols.Select(s => $"    public const uint {UniqueName(s.Name, s.Address, used)} = 0x{s.Address:X8};"),
            "}",
        ]);
    }

    private string CallName(Function function) => $"Funcs.{FunctionName(function)}";

    private static string Lines(IEnumerable<string> lines) => string.Concat(lines.Select(line => line + "\n"));

    private static Dictionary<uint, string> AssignFunctionNames(IEnumerable<Function> functions)
    {
        var used = new HashSet<string>();
        return functions.ToDictionary(f => f.Address, f => UniqueName(f.Name, f.Address, used));
    }

    private static string UniqueName(string symbol, uint address, HashSet<string> used)
    {
        var builder = new StringBuilder(symbol.Length + 1);
        foreach (char c in symbol)
        {
            builder.Append(char.IsAsciiLetterOrDigit(c) || c == '_' ? c : '_');
        }

        if (char.IsAsciiDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        string name = builder.ToString();
        if (!used.Add(name))
        {
            name = $"{name}_{address:X8}";
            used.Add(name);
        }

        return name;
    }

    private sealed class FunctionWriter
    {
        private readonly CSharpGenerator _generator;
        private readonly FunctionAnalysis _analysis;
        private readonly Dictionary<uint, StatusFlags> _liveFlags;
        private readonly StringBuilder _output = new();
        private readonly Instruction[] _instructions;
        private readonly List<string> _body = [];
        private readonly Dictionary<uint, CodeCycles> _executedCycles = [];
        private int _indent = 1;

        public FunctionWriter(CSharpGenerator generator, FunctionAnalysis analysis)
        {
            _generator = generator;
            _analysis = analysis;
            _liveFlags = FlagLiveness.Compute(analysis);
            _instructions = [.. analysis.Instructions];
        }

        private Function Function => _analysis.Function;

        public string Write()
        {
            string name = _generator.FunctionName(Function);
            Line($"public static void {name}(RecompContext ctx) => Patches.{name}(ctx);");
            _output.Append('\n');
            Line("public static partial class Original");
            Line("{");
            _indent++;

            Line($"public static void {name}(RecompContext ctx)");
            Line("{");
            _indent++;

            if (_generator._context.TraceMode)
            {
                Line($"TraceEntry(\"{Function.Name}\");");
            }

            WriteHook(0);

            if (_analysis.Flows.Values.Any(f => f.Kind == FlowKind.IndirectJump))
            {
                Line("uint returnAddress = ctx.R14 & ~1u;");
            }

            var loopHeads = FindLoopHeads();
            var blockCycles = CountBlockCycles();

            for (int n = 0; n < _instructions.Length; n++)
            {
                var instruction = _instructions[n];
                uint address = instruction.Address;

                if (_analysis.Labels.Contains(address))
                {
                    _indent--;
                    Line($"L_{address:X8}:");
                    _indent++;
                }

                if (blockCycles.TryGetValue(address, out var cycles))
                {
                    Line($"Scheduler.Cycles += {cycles};");

                    if (n == 0 || loopHeads.Contains(address))
                    {
                        Line(EventCheck);
                    }
                }

                WriteHook(address);
                Line($"// {address:X8}: {Disassembler.Format(instruction)}");
                WriteInstruction(instruction);

                bool isLast = n == _instructions.Length - 1;
                var flow = _analysis.Flows.GetValueOrDefault(address);
                if (isLast && flow.FallsThrough(instruction) && _analysis.FallsThroughTo is { } next)
                {
                    Line($"{_generator.CallName(next)}(ctx);");
                }
            }

            _indent--;
            Line("}");
            _indent--;
            Line("}");

            return _output.ToString();
        }

        private void WriteHook(uint beforeAddress)
        {
            foreach (var hook in _generator._context.Hooks[Function.Name].Where(h => h.BeforeAddress == beforeAddress))
            {
                foreach (string line in hook.Text.Trim().Split('\n'))
                {
                    Line(line.TrimEnd());
                }
            }
        }

        private HashSet<uint> FindLoopHeads()
        {
            var loopHeads = new HashSet<uint>();
            foreach (var (address, flow) in _analysis.Flows)
            {
                loopHeads.UnionWith(flow.LocalTargets.Where(t => t <= address));
            }

            return loopHeads;
        }

        private Dictionary<uint, CodeCycles> CountBlockCycles()
        {
            var blockCycles = new Dictionary<uint, CodeCycles>();
            var cycles = new CodeCycles(Function.Region);
            bool startsBlock = true;
            bool isPrefetched = false;

            foreach (var instruction in _instructions)
            {
                if (startsBlock || _analysis.Labels.Contains(instruction.Address))
                {
                    cycles = new CodeCycles(Function.Region);
                    blockCycles[instruction.Address] = cycles;
                    isPrefetched = false;
                }

                uint fetched = instruction.Address + (instruction.IsThumb ? 4u : 8u);
                var fetch = CycleCosts.FirstFetch(instruction, isPrefetched);
                var executed = cycles;
                if (instruction.Condition == Condition.AL)
                {
                    cycles.Add(fetch, instruction.Size / 2, isWordAccess: !instruction.IsThumb, fetched);
                    cycles.Internal += CycleCosts.FixedInternal(instruction);
                }
                else
                {
                    var skipped = isPrefetched ? Fetch.PrefetchedOrSequential : Fetch.Sequential;
                    cycles.Add(skipped, instruction.Size / 2, isWordAccess: !instruction.IsThumb, fetched);
                    executed = new CodeCycles(Function.Region);
                    if (Function.RunsFromROM)
                    {
                        executed.Replace(skipped, fetch, fetched);
                    }
                }

                if (IsLiteralLoad(instruction))
                {
                    executed.Add(Fetch.NonSequential, 2, isWordAccess: true, instruction.LiteralAddress);
                }

                if (executed != cycles && !executed.IsEmpty)
                {
                    _executedCycles[instruction.Address] = executed;
                }

                isPrefetched = CycleCosts.HasInternalCycles(instruction) || CycleCosts.AccessesMemory(instruction);
                startsBlock = _analysis.Flows.GetValueOrDefault(instruction.Address).Kind != FlowKind.Next;
            }

            return blockCycles;
        }

        private bool IsLiteralLoad(Instruction i)
        {
            if (i is not { Opcode: Opcode.Ldr, Rn: PC, OperandKind: OperandKind.Immediate, PreIndexed: true, WriteBack: false }
                || i.Rd == PC)
            {
                return false;
            }

            uint address = i.LiteralAddress;
            return address >= Function.Address && address + 4 <= Function.End;
        }

        private string OpenBus(Instruction i)
        {
            return Function.Region == CodeRegion.CopiedToRAM
                ? $"(Recomp.IsCopyInEWRAM ? 0x{OpenBus(i, CodeRegion.EWRAM):X8}u : 0x{OpenBus(i, CodeRegion.IWRAM):X8}u)"
                : $"0x{OpenBus(i, Function.Region):X8}u";
        }

        private uint OpenBus(Instruction i, CodeRegion region)
        {
            uint At(uint offset) => _generator._context.ReadOpcode16(Function, i.Address + offset);

            bool isAligned = (i.Address & 2) == 0;
            return (i.IsThumb, region) switch
            {
                (false, _) => At(8) | (At(10) << 16),
                (true, CodeRegion.BIOS or CodeRegion.OAM) => isAligned ? At(4) | (At(6) << 16) : At(2) | (At(4) << 16),
                (true, CodeRegion.IWRAM) => isAligned ? At(4) | (At(2) << 16) : At(2) | (At(4) << 16),
                _ => At(4) * 0x10001u,
            };
        }

        private void EmitJumpCycles(CodeRegion region, bool isThumb)
        {
            var cycles = new CodeCycles(region);
            CycleCosts.AddJumpCycles(cycles, isThumb);
            Emit($"Scheduler.Cycles += {cycles};");
        }

        private void WriteInstruction(Instruction i)
        {
            int outerIndent = _indent;
            _indent = 0;
            if (i.Condition != Condition.AL)
            {
                var executed = _executedCycles.GetValueOrDefault(i.Address) ?? new CodeCycles(Function.Region);
                executed.Internal = CycleCosts.FixedInternal(i);
                if (!executed.IsEmpty)
                {
                    Emit($"Scheduler.Cycles += {executed};");
                }
            }

            WriteBody(i);
            _indent = outerIndent;

            if (_body.Count == 0)
            {
                return;
            }

            bool isConditional = i.Condition != Condition.AL;
            if (isConditional)
            {
                Line($"if ({ConditionExpression(i.Condition)})");
            }

            if (_body.Count == 1 && !isConditional)
            {
                Line(_body[0]);
            }
            else
            {
                Line("{");
                foreach (string line in _body)
                {
                    Line("    " + line);
                }

                Line("}");
            }

            _body.Clear();
        }

        private void WriteBody(Instruction i)
        {
            switch (i.Opcode)
            {
                case <= Opcode.Mvn:
                    WriteDataProcessing(i);
                    break;
                case Opcode.Mul or Opcode.Mla:
                    WriteMultiply(i);
                    break;
                case Opcode.Umull or Opcode.Umlal or Opcode.Smull or Opcode.Smlal:
                    WriteMultiplyLong(i);
                    break;
                case Opcode.B or Opcode.Bl:
                    WriteBranch(i);
                    break;
                case Opcode.Bx:
                    Emit($"uint target = {Register(i, i.Rm)};");
                    WriteIndirectBranch(i);
                    break;
                case Opcode.Ldr or Opcode.Ldrb or Opcode.Ldrh or Opcode.Ldrsb or Opcode.Ldrsh:
                    WriteLoad(i);
                    break;
                case Opcode.Str or Opcode.Strb or Opcode.Strh:
                    WriteStore(i);
                    break;
                case Opcode.Ldm:
                    WriteLoadMultiple(i);
                    break;
                case Opcode.Stm:
                    WriteStoreMultiple(i);
                    break;
                case Opcode.Swp or Opcode.Swpb:
                    WriteSwap(i);
                    break;
                case Opcode.Mrs:
                    Emit($"ctx.R{i.Rd} = ctx.{(i.UsesSPSR ? "SPSR" : "CPSR")};");
                    break;
                case Opcode.Msr:
                    Emit($"ctx.Write{(i.UsesSPSR ? "SPSR" : "CPSR")}({OperandExpression(i)}, 0b{Convert.ToString(i.PSRFieldMask, 2).PadLeft(4, '0')});");
                    if (!i.UsesSPSR && (i.PSRFieldMask & 1) != 0)
                    {
                        Emit(EventCheck);
                    }

                    break;
                case Opcode.Swi:
                    EmitJumpCycles(CodeRegion.BIOS, isThumb: false);
                    Emit($"Recomp.SWI(ctx, 0x{i.BIOSFunction:X2});");
                    EmitJumpCycles(Function.Region, i.IsThumb);
                    break;
                case Opcode.Trap:
                    string reason = i.Encoding == 0xEFFF ? "Emulator assertion stop" : "Undefined-instruction trap";
                    Emit($"throw new System.InvalidOperationException(\"{reason} in {Function.Name} at 0x{i.Address:X8} (0x{i.Encoding:X4}).\");");
                    break;
                default:
                    throw new UnreachableException();
            }
        }

        private void WriteDataProcessing(Instruction i)
        {
            bool isLogical = i.Opcode is Opcode.And or Opcode.Eor or Opcode.Tst or Opcode.Teq
                or Opcode.Orr or Opcode.Mov or Opcode.Bic or Opcode.Mvn;
            var flags = FlagLiveness.Writes(i) & _liveFlags[i.Address];
            bool writesPC = i.Rd == PC && !i.IsCompare;
            bool needsCarry = isLogical && i.SetsFlags && _liveFlags[i.Address].HasFlag(StatusFlags.C)
                && (FlagLiveness.HasShifterCarry(i) || i.OperandKind == OperandKind.RegisterShift);

            string rn = Register(i, i.Rn);
            string operand = OperandExpression(i);
            string carryIn = "(ctx.C ? 1u : 0u)";
            string borrow = "(ctx.C ? 0u : 1u)";

            if (!isLogical && (flags & (StatusFlags.C | StatusFlags.V)) != 0)
            {
                Emit($"uint rn = {rn};");
                Emit($"uint operand = {operand};");
                (rn, operand) = ("rn", "operand");

                if (i.Opcode == Opcode.Adc)
                {
                    Emit($"uint carryIn = {carryIn};");
                    carryIn = "carryIn";
                }
                else if (i.Opcode is Opcode.Sbc or Opcode.Rsc)
                {
                    Emit($"uint borrow = {borrow};");
                    borrow = "borrow";
                }
            }

            string result = i.Opcode switch
            {
                Opcode.And or Opcode.Tst => $"{rn} & {operand}",
                Opcode.Eor or Opcode.Teq => $"{rn} ^ {operand}",
                Opcode.Sub or Opcode.Cmp => $"{rn} - {operand}",
                Opcode.Rsb => $"{operand} - {rn}",
                Opcode.Add or Opcode.Cmn => $"{rn} + {operand}",
                Opcode.Adc => $"{rn} + {operand} + {carryIn}",
                Opcode.Sbc => $"{rn} - {operand} - {borrow}",
                Opcode.Rsc => $"{operand} - {rn} - {borrow}",
                Opcode.Orr => $"{rn} | {operand}",
                Opcode.Mov => operand,
                Opcode.Bic => $"{rn} & ~{operand}",
                _ => $"~{operand}",
            };

            if (flags == StatusFlags.None && !needsCarry)
            {
                if (operand == "0x0u" && i.Opcode is Opcode.Add or Opcode.Sub)
                {
                    result = rn;
                }

                if (writesPC)
                {
                    Emit($"uint target = {result};");
                    WriteIndirectBranch(i);
                }
                else if (!i.IsCompare && result != $"ctx.R{i.Rd}")
                {
                    Emit($"ctx.R{i.Rd} = {result};");
                }

                return;
            }

            Emit($"uint result = {result};");
            WriteFlag(flags, StatusFlags.N, "(int)result < 0");
            WriteFlag(flags, StatusFlags.Z, "result == 0");

            if (needsCarry)
            {
                Emit($"ctx.C = {CarryExpression(i)};");
            }

            (string left, string right) = i.Opcode is Opcode.Rsb or Opcode.Rsc ? (operand, rn) : (rn, operand);
            switch (i.Opcode)
            {
                case Opcode.Add or Opcode.Cmn:
                    WriteFlag(flags, StatusFlags.C, "result < rn");
                    WriteFlag(flags, StatusFlags.V, "(int)((rn ^ result) & (operand ^ result)) < 0");
                    break;
                case Opcode.Adc:
                    WriteFlag(flags, StatusFlags.C, "(ulong)rn + operand + carryIn > uint.MaxValue");
                    WriteFlag(flags, StatusFlags.V, "(int)((rn ^ result) & (operand ^ result)) < 0");
                    break;
                case Opcode.Sub or Opcode.Cmp or Opcode.Rsb:
                    WriteFlag(flags, StatusFlags.C, $"{left} >= {right}");
                    WriteFlag(flags, StatusFlags.V, $"(int)(({left} ^ {right}) & ({left} ^ result)) < 0");
                    break;
                case Opcode.Sbc or Opcode.Rsc:
                    WriteFlag(flags, StatusFlags.C, $"(ulong){left} >= (ulong){right} + borrow");
                    WriteFlag(flags, StatusFlags.V, $"(int)(({left} ^ {right}) & ({left} ^ result)) < 0");
                    break;
            }

            if (!i.IsCompare)
            {
                Emit($"ctx.R{i.Rd} = result;");
            }
        }

        private void WriteFlag(StatusFlags needed, StatusFlags flag, string expression)
        {
            if (needed.HasFlag(flag))
            {
                Emit($"ctx.{flag} = {expression};");
            }
        }

        private string OperandExpression(Instruction i)
        {
            string rm = Register(i, i.Rm);
            switch (i.OperandKind)
            {
                case OperandKind.Immediate:
                    return $"0x{i.Immediate:X}u";
                case OperandKind.RegisterShift:
                    return $"Shifter.{i.ShiftType}({rm}, ctx.R{i.Rs} & 0xFF)";
            }

            int amount = i.ShiftAmount;
            if (amount == 0)
            {
                return rm;
            }

            return i.ShiftType switch
            {
                ShiftType.LSL => $"({rm} << {amount})",
                ShiftType.LSR => amount == 32 ? "0u" : $"({rm} >> {amount})",
                ShiftType.ASR => $"(uint)((int){rm} >> {Math.Min(amount, 31)})",
                ShiftType.ROR => $"uint.RotateRight({rm}, {amount})",
                _ => $"(({rm} >> 1) | (ctx.C ? 0x80000000u : 0u))",
            };
        }

        private string CarryExpression(Instruction i)
        {
            string rm = Register(i, i.Rm);
            switch (i.OperandKind)
            {
                case OperandKind.Immediate:
                    return (i.Immediate >> 31) != 0 ? "true" : "false";
                case OperandKind.RegisterShift:
                    return $"Shifter.{i.ShiftType}Carry({rm}, ctx.R{i.Rs} & 0xFF, ctx.C)";
            }

            int bit = i.ShiftType == ShiftType.LSL ? 32 - i.ShiftAmount : i.ShiftAmount - 1;
            return $"({rm} & 0x{1u << bit:X}u) != 0";
        }

        private void WriteMultiply(Instruction i)
        {
            string accumulate = i.Opcode == Opcode.Mla ? $" + ctx.R{i.Rn}" : "";
            Emit($"Scheduler.Cycles += {(i.Opcode == Opcode.Mla ? "1 + " : "")}CPUTiming.Multiply(ctx.R{i.Rs});");
            Emit($"uint result = ctx.R{i.Rm} * ctx.R{i.Rs}{accumulate};");
            Emit($"ctx.R{i.Rd} = result;");

            var flags = FlagLiveness.Writes(i) & _liveFlags[i.Address];
            WriteFlag(flags, StatusFlags.N, "(int)result < 0");
            WriteFlag(flags, StatusFlags.Z, "result == 0");
        }

        private void WriteMultiplyLong(Instruction i)
        {
            bool isSigned = i.Opcode is Opcode.Smull or Opcode.Smlal;
            string extra = i.Opcode is Opcode.Umlal or Opcode.Smlal ? "2" : "1";
            Emit($"Scheduler.Cycles += {extra} + CPUTiming.{(isSigned ? "Multiply" : "UnsignedMultiply")}(ctx.R{i.Rs});");
            string product = isSigned
                ? $"(ulong)((long)(int)ctx.R{i.Rm} * (int)ctx.R{i.Rs})"
                : $"(ulong)ctx.R{i.Rm} * ctx.R{i.Rs}";

            if (i.Opcode is Opcode.Umlal or Opcode.Smlal)
            {
                product += $" + (((ulong)ctx.R{i.Rd} << 32) | ctx.R{i.Rn})";
            }

            Emit($"ulong result = {product};");
            Emit($"ctx.R{i.Rn} = (uint)result;");
            Emit($"ctx.R{i.Rd} = (uint)(result >> 32);");

            var flags = FlagLiveness.Writes(i) & _liveFlags[i.Address];
            WriteFlag(flags, StatusFlags.N, "(long)result < 0");
            WriteFlag(flags, StatusFlags.Z, "result == 0");
        }

        private void WriteBranch(Instruction i)
        {
            var flow = _analysis.Flows[i.Address];
            var callee = flow.Kind is FlowKind.Branch ? null : _generator._context.FindFunction(flow.Target)!;
            EmitJumpCycles(callee?.Region ?? Function.Region, callee?.IsThumb ?? i.IsThumb);

            uint returnAddress = i.Address + 4;
            if (i.Opcode == Opcode.Bl)
            {
                Emit($"ctx.R14 = {PCValue(i.IsThumb ? returnAddress | 1 : returnAddress)};");
            }

            switch (flow.Kind)
            {
                case FlowKind.Branch:
                    Emit($"goto L_{flow.Target:X8};");
                    break;
                case FlowKind.Call:
                    Emit($"{CalleeName(flow.Target)}(ctx);");
                    EmitUnwindCheck(returnAddress);
                    break;
                default:
                    Emit($"{CalleeName(flow.Target)}(ctx);");
                    EmitUnwindCheck(returnAddress: null);
                    Emit("return;");
                    break;
            }
        }

        private string CalleeName(uint address) => _generator.CallName(_generator._context.FindFunction(address)!);

        private void WriteIndirectBranch(Instruction i)
        {
            var flow = _analysis.Flows[i.Address];
            switch (flow.Kind)
            {
                case FlowKind.BranchExchange:
                    EmitJumpCycles(Function.Region, (flow.Target & 1) != 0);
                    Emit($"goto L_{flow.Target & ~1u:X8};");
                    break;

                case FlowKind.IndirectCall:
                    EmitJumpCyclesTo(i);
                    Emit("Recomp.LookupFunc(target)(ctx);");
                    EmitUnwindCheck(flow.Target);
                    Emit($"goto L_{flow.Target:X8};");
                    break;

                case FlowKind.JumpTable:
                    EmitJumpCycles(Function.Region, i.IsThumb);
                    string dispatch = flow.PCRelativeTargets && Function.IsCopiedToRAM
                        ? "(target & ~1u) - Recomp.CopyOffset" : "target & ~1u";
                    Emit($"switch ({dispatch})");
                    Emit("{");
                    _indent++;
                    foreach (uint target in flow.Targets!)
                    {
                        Emit($"case 0x{target:X8}u: goto L_{target:X8};");
                    }

                    Emit($"default: throw Recomp.SwitchError(\"{Function.Name}\", 0x{i.Address:X8}u, target);");
                    _indent--;
                    Emit("}");
                    break;

                default:
                    EmitJumpCyclesTo(i);
                    Emit("if ((target & ~1u) != returnAddress)");
                    Emit("{");
                    _indent++;
                    if (Function.Size > 2)
                    {
                        string address = Function.IsCopiedToRAM ? "(target & ~1u) - Recomp.CopyOffset" : "(target & ~1u)";
                        Emit($"if ({address} - 0x{Function.Address + 2:X8}u < 0x{Function.Size - 2:X}u) throw Recomp.JumpError(\"{Function.Name}\", 0x{i.Address:X8}u, target);");
                    }

                    Emit("Recomp.IndirectJump(ctx, target);");
                    EmitUnwindCheck(returnAddress: null);
                    _indent--;
                    Emit("}");
                    Emit("return;");
                    break;
            }
        }

        private void EmitUnwindCheck(uint? returnAddress)
        {
            var pads = _analysis.LandingPads.Where(p => p != returnAddress).ToList();
            string? resume = returnAddress is { } address ? $"Recomp.TryResumeAt({PCValue(address)})" : null;
            if (pads.Count == 0)
            {
                if (resume is not null)
                {
                    Emit($"if (Recomp.IsUnwinding && !{resume}) return;");
                }

                return;
            }

            Emit("if (Recomp.IsUnwinding)");
            Emit("{");
            _indent++;
            foreach (uint pad in pads)
            {
                Emit($"if (Recomp.TryResumeAt({PCValue(pad)})) goto L_{pad:X8};");
            }

            if (resume is not null)
            {
                Emit($"if (!{resume}) return;");
            }

            _indent--;
            Emit("}");
        }

        private string PCValue(uint value)
        {
            return Function.IsCopiedToRAM ? $"(0x{value:X8}u + Recomp.CopyOffset)" : $"0x{value:X8}u";
        }

        private void EmitJumpCyclesTo(Instruction i)
        {
            string isThumb = i.Opcode == Opcode.Bx ? "(target & 1) != 0" : i.IsThumb ? "true" : "false";
            Emit($"Scheduler.Cycles += CPUTiming.JumpCycles(target, {isThumb});");
        }

        private void WriteLoad(Instruction i)
        {
            if (IsLiteralLoad(i))
            {
                Emit($"ctx.R{i.Rd} = 0x{_generator._context.ReadUInt32(Function, i.LiteralAddress):X8}u;");
                return;
            }

            string address = WriteAddress(i, writeBackFirst: true);
            string openBus = OpenBus(i);
            string value = i.Opcode switch
            {
                Opcode.Ldr => $"Loads.Word({address}, {openBus})",
                Opcode.Ldrb => $"Memory.Read8({address}, {openBus})",
                Opcode.Ldrh => $"Loads.Halfword({address}, {openBus})",
                Opcode.Ldrsb => $"(uint)(sbyte)Memory.Read8({address}, {openBus})",
                _ => $"Loads.SignedHalfword({address}, {openBus})",
            };

            if (i.Rd == PC)
            {
                Emit($"uint target = {value};");
                WriteIndirectBranch(i);
            }
            else
            {
                Emit($"ctx.R{i.Rd} = {value};");
            }
        }

        private void WriteStore(Instruction i)
        {
            string address = WriteAddress(i, writeBackFirst: false);

            string value = i.Rd == PC ? PCValue(i.Address + 12) : $"ctx.R{i.Rd}";
            Emit(i.Opcode switch
            {
                Opcode.Str => $"Memory.Write32({address}, {value});",
                Opcode.Strb => $"Memory.Write8({address}, (byte){value});",
                _ => $"Memory.Write16({address}, (ushort){value});",
            });

            if (i.WriteBack)
            {
                Emit($"ctx.R{i.Rn} = newBase;");
            }
        }

        private string WriteAddress(Instruction i, bool writeBackFirst)
        {
            string rn = i.Rn == PC ? PCValue(i.AlignedPC) : $"ctx.R{i.Rn}";
            string offset = OperandExpression(i);
            string indexed = offset == "0x0u" ? rn : $"{rn} {(i.AddOffset ? '+' : '-')} {offset}";

            if (!i.WriteBack)
            {
                return i.PreIndexed ? indexed : rn;
            }

            Emit($"uint newBase = {indexed};");
            Emit($"uint address = {(i.PreIndexed ? "newBase" : rn)};");

            if (writeBackFirst && i.Rd != i.Rn)
            {
                Emit($"ctx.R{i.Rn} = newBase;");
            }

            return "address";
        }

        private void WriteLoadMultiple(Instruction i)
        {
            var registers = RegisterList(i);
            WriteBlockStart(i, registers.Count);

            bool loadsPC = registers.Contains(PC);
            for (int n = 0; n < registers.Count; n++)
            {
                string destination = registers[n] == PC ? "uint target" : $"ctx.R{registers[n]}";
                Emit($"{destination} = Memory.Read32({Offset("address", n * 4)}, {OpenBus(i)});");
            }

            WriteSequentialSaving(registers.Count);

            if (i.WriteBack && !registers.Contains(i.Rn))
            {
                Emit($"ctx.R{i.Rn} = {NewBase(i, registers.Count)};");
            }

            if (loadsPC)
            {
                WriteIndirectBranch(i);
            }
        }

        private void WriteStoreMultiple(Instruction i)
        {
            var registers = RegisterList(i);
            WriteBlockStart(i, registers.Count);

            bool writeBackFirst = i.WriteBack && registers.Contains(i.Rn) && registers[0] != i.Rn;
            if (writeBackFirst)
            {
                Emit($"ctx.R{i.Rn} = {NewBase(i, registers.Count)};");
            }

            for (int n = 0; n < registers.Count; n++)
            {
                string value = registers[n] == PC ? PCValue(i.Address + 12) : $"ctx.R{registers[n]}";
                Emit($"Memory.Write32({Offset("address", n * 4)}, {value});");
            }

            WriteSequentialSaving(registers.Count);

            if (i.WriteBack && !writeBackFirst)
            {
                Emit($"ctx.R{i.Rn} = {NewBase(i, registers.Count)};");
            }
        }

        private static List<byte> RegisterList(Instruction i)
        {
            return [.. Enumerable.Range(0, 16).Where(r => (i.RegisterList & (1 << r)) != 0).Select(r => (byte)r)];
        }

        private void WriteSequentialSaving(int count)
        {
            if (count > 1)
            {
                Emit($"Scheduler.Cycles -= CPUTiming.SequentialSaving(address, {count});");
            }
        }

        private void WriteBlockStart(Instruction i, int count)
        {
            Emit($"uint baseAddress = ctx.R{i.Rn};");

            int start = (i.AddOffset, i.PreIndexed) switch
            {
                (true, false) => 0,
                (true, true) => 4,
                (false, false) => 4 - (count * 4),
                (false, true) => -count * 4,
            };

            Emit(start switch
            {
                0 => "uint address = baseAddress;",
                > 0 => $"uint address = baseAddress + {start};",
                < 0 => $"uint address = baseAddress - {-start};",
            });
        }

        private static string Offset(string address, int offset) => offset == 0 ? address : $"{address} + {offset}";

        private static string NewBase(Instruction i, int count)
        {
            return $"baseAddress {(i.AddOffset ? '+' : '-')} {count * 4}";
        }

        private void WriteSwap(Instruction i)
        {
            Emit($"uint address = ctx.R{i.Rn};");
            if (i.Opcode == Opcode.Swp)
            {
                Emit($"uint value = Loads.Word(address, {OpenBus(i)});");
                Emit($"Memory.Write32(address, ctx.R{i.Rm});");
            }
            else
            {
                Emit($"uint value = Memory.Read8(address, {OpenBus(i)});");
                Emit($"Memory.Write8(address, (byte)ctx.R{i.Rm});");
            }

            Emit($"ctx.R{i.Rd} = value;");
        }

        private string Register(Instruction i, byte register)
        {
            if (register != PC)
            {
                return $"ctx.R{register}";
            }

            bool isAligned = i is { Opcode: Opcode.Add, Rn: PC, OperandKind: OperandKind.Immediate } or { Opcode: Opcode.Bx, IsThumb: true };
            uint value = isAligned ? i.AlignedPC
                : i.OperandKind == OperandKind.RegisterShift ? i.Address + 12
                : i.Address + (i.IsThumb ? 4u : 8u);
            return PCValue(value);
        }

        private static string ConditionExpression(Condition condition) => condition switch
        {
            Condition.EQ => "ctx.Z",
            Condition.NE => "!ctx.Z",
            Condition.CS => "ctx.C",
            Condition.CC => "!ctx.C",
            Condition.MI => "ctx.N",
            Condition.PL => "!ctx.N",
            Condition.VS => "ctx.V",
            Condition.VC => "!ctx.V",
            Condition.HI => "ctx.C && !ctx.Z",
            Condition.LS => "!ctx.C || ctx.Z",
            Condition.GE => "ctx.N == ctx.V",
            Condition.LT => "ctx.N != ctx.V",
            Condition.GT => "!ctx.Z && ctx.N == ctx.V",
            _ => "ctx.Z || ctx.N != ctx.V",
        };

        private void Line(string text)
        {
            _output.Append(' ', _indent * 4).Append(text).Append('\n');
        }

        private void Emit(string text)
        {
            _body.Add(new string(' ', _indent * 4) + text);
        }
    }
}
